--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Terpz710/CustomBossBar
build-by-default: true
branches:
- main
projects:
  CustomBossBar:
    path: ""
    libs:
      - src: Terpz710/apibossbar/apibossbar
        version: ^0.0.5
...
